### ISSUE TITLE
Using a custom model

### ISSUE THREAD

**Issue by GorkaAbad** [ain-soph/trojanzoo#162]
Hi,
Can I use a custom poisoned model for evaluating it against a defense, i.e., Neural Cleanse?

I'm trying to implement it with no success. I'm checking the documentation and the code but I cannot understand how to make it work. Can someone provide more info on this?

Thanks in advance

**Comment by ain-soph** [comment]
There are certain modules in trojanzoo workflow: dataset, model, mark, attack, defense.

Since you have already got a poisoned model, please import it in `model` module.

- If it's an existing model architecture (e.g., resnet18), you only need to import the weight parameters using `model.load()` (You may need to change layer names to get adapted to trojanzoo style.)
- If not, you need to register your own model class (one `_ImageModel` and another `ImageModel`, see how [resnet](https://github.com/ain-soph/trojanzoo/blob/main/trojanvision/models/torchvision/resnet.py) works.)

Afterwards, you could use all existing defenses with setting attack as `--attack badnet`. You need to provide mark image or tensor to `mark` module.

**Comment by GorkaAbad** [comment]
Thanks for your reply.
I have added the model to the module and I use the `---pretrained` flag for loading the poisoned weights from a `.pth`.
However, I cannot add my mark to `mark` module. I keep getting this error:
`'NoneType' object has no attribute 'add_mark'`.
I have already added the image to the `marks` folder.

Any suggestions?
Thanks

**Comment by GorkaAbad** [comment]
Okay, I think I make it work for my use case. However, I cannot see the anomaly score for my model when using Neural Cleanse. Is there anything similar in trojanzoo?

Thanks in advance

**Comment by ain-soph** [comment]
MAD is the anomaly score.
