### ISSUE TITLE
strange mark saved 

### ISSUE THREAD

**Issue by andyclsr** [ain-soph/trojanzoo#186]
![image](https://user-images.githubusercontent.com/69943589/229446102-3055fe11-7a29-4746-b6b9-04e561cf2337.png)
the picture above is the mark saved and left are the saved filename. Apparently, it should be a white square but with this strange thing
what happened?
below is the setting 
![image](https://user-images.githubusercontent.com/69943589/229446820-53dd72d6-dabf-401a-825e-285d27c840a1.png)

**Comment by ain-soph** [comment]
mark_random_init in mark instance will set all pixels as random values. Please read the docs carefully.

And it seems you are using an old version of trojanzoo (the argument name is random_init instead of mark_random_init)

https://ain-soph.github.io/trojanzoo/trojanvision/marks.html#trojanvision.marks.Watermark

**Comment by andyclsr** [comment]
thank you for generous explanations ! this is really my mislook :(
wish you a great day!
