### ISSUE TITLE
Attacking MNIST trained models

### ISSUE THREAD

**Issue by SidharthAgarwal18** [ain-soph/trojanzoo#66]
Hi, so I was trying to attack MNIST fine-tuned resnet model with trojanNN and I got this error on my terminal.

"line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[512, 1, 32, 32] to have 3 channels, but got 1 channels instead"

Can someone please help me resolve this, is this because MNIST is grayscale?

**Comment by ain-soph** [comment]
Thanks for using TrojanZoo!!!  
Why you would use ResNet on MNIST... ResNet first conv layer requires 3 input channels (RGB), but MNIST is grey images. 
It's too auxiliary to apply ResNet on MNIST. Just use the default simple `Net` (which is a small convnet and you'll get 99% acc.)
Just use lr=0.01 I guess.

I can provide a training command:
```
python examples/train.py --verbose 1 --color --dataset mnist --lr 0.01 --save
```
Not quite sure about lr, you may test different settings, but I think it'll be good since it's a over-simple dataset.

**Comment by ain-soph** [comment]
Just to add that, MNIST behaves very differently from large-scale datasets.  
So I never test attacks/defenses on MNIST.

The typical dataset we use is CIFAR10.
